browniebroke/deezer-python

.travis.yml, setup.py
=> Run tests against Python 3.5

deezer/resources.py, deezer/tests/test_resources.py
add functions to iterate resources
add possibility to pass custom parameters to resource functions
=> add resource parameters and iterators

deezer/client.py, deezer/resources.py
As i wasn't convinced with previous implementation, i searched another way to do it and finally found this alternative which contains less specific code. Or at least it's placed where it belongs to.
No more specific code related to chart in common method but in chart resource.
I also added the possibility to use limit param on some method, like getting top track for an artist.
=> Improve chart integration

.github/PULL_REQUEST_TEMPLATE.md, .travis.yml, CONTRIBUTING.rst, README.rst, deezer/__init__.py, docs/source/api_reference.rst, docs/source/async.rst, docs/source/authors.rst, docs/source/conf.py, docs/source/contributing.rst, docs/source/index.rst, docs/source/license.rst, docs/source/readme.rst, tox.ini
- Structure the pages on RTD
- Pull requests template
- Update contributors guidelines
=> Docs enhancements

deezer/client.py, tox.ini
=> Run Flake8 on Travis

deezer/client.py
=> Store the session in the client

appveyor.yml, appveyor/install.ps1, appveyor/run_with_env.cmd, deezer/tests/base.py, setup.py
=> Appveyor tests

.travis.yml, requirements-test.txt, setup.cfg, tox.ini
Make sure all the status check are still green. Fixes #21.
=> Add a CI step for check-manifest

HISTORY.rst, deezer/client.py, tests/test_client_parameter.py
Added index and limit parameters to search and get_chart. Set the defaults to what Deezer's defaults are. 
Fixes #31
=> Pagination feature

CONTRIBUTING.rst, README.rst, deezer/__init__.py, deezer/client.py, deezer/contrib/tornado.py, deezer/resources.py, setup.py, tests/base.py, tests/test_client_parameter.py, tests/test_resources.py, tox.ini
=> Auto-format code using black

.travis.yml, CONTRIBUTING.rst, HISTORY.rst, appveyor.yml, setup.py, tox.ini
=> Drop support for EOL Python 3.4

.github/PULL_REQUEST_TEMPLATE.md
- [n/a] Include tests for bug fix and new functionality
- [n/a] Added an entry at the top of History.rst, under the unreleased section
=> Update template to match filename

README.md
=> Update Travis CI badge: travis.org -> travis.com

.github/workflows/pythonpackage.yml
=> Create pythonpackage.yml to enable GitHub actions

HISTORY.rst, deezer/client.py, tests/base.py, tests/cassettes/TestClient.test_with_language_header_fr.yaml, tests/cassettes/TestClient.test_with_language_header_ja.yaml, tests/test_client_parameter.py
=> Add a header kwarg in Client to force session headers

.github/workflows/tests.yml
=> Update names in Github action & run on Python 3.8

.travis.yml
=> Use Python 3.8 on Travis (drop the -dev)

deezer/client.py
Should help with documentation & IDE integrations.
=> Use explicit kwargs for the Client class

.pre-commit-config.yaml, deezer/client.py
Add several useful hooks and fix the existing one.
=> Enhance pre-commit hook setup

deezer/resources.py, docs/source/conf.py
Link to official API docs & explain fields as attributes
=> Improve documentation for resources

conftest.py, deezer/resources.py, requirements-test.txt, tests/cassettes/TestPlaylist.test_get_fans.yaml, tests/cassettes/TestPlaylist.test_get_tracks.yaml, tests/test_resources.py
=> Add `get_tracks` and `get_fans` methods to `Playlist` resources

.github/workflows/docs.yml, .github/workflows/lint.yml, .github/workflows/tests.yml, .readthedocs.yml, docs/requirements.txt, requirements-test.txt, requirements.txt, tox.ini
=> 🧹 Clean up project requirements

.github/workflows/tests.yml, requirements.in, requirements.txt
=> Use codecov-action to upload coverage report

.github/workflows/lint.yml, .github/workflows/tests.yml, requirements.in, requirements.txt
=> Fix missing requirements when running tests

MANIFEST.in, requirements.in, requirements.txt, setup.cfg, tox.ini
=> Remove check-manifest package

.github/workflows/ci.yml, requirements.in, setup.cfg, tox.ini
Refs: https://github.com/browniebroke/deezer-python/issues/166
Fixes: https://github.com/browniebroke/deezer-python/issues/166
BREAKING CHANGE: Depreciate python 3.5
Did I had the commit message correctly? @browniebroke
=> feat: drop support for Python 3.5

.github/workflows/ci.yml, CONTRIBUTING.md, setup.cfg, tox.ini
=> Add support for python 3.9

poetry.lock, pyproject.toml
=> Fix Poetry's extras

.github/workflows/ci.yml, .github/workflows/semantic-release.yml
=> fix: release in a separate environment

deezer/client.py, deezer/resources.py, tests/test_resources.py
=> feat: deprecate the `asdict` method from the `Resource` class

poetry.lock
=> chore: run poetry update

.github/workflows/ci.yml, .pre-commit-config.yaml, deezer/__init__.py, deezer/client.py, deezer/resources.py, docs/source/conf.py
=> refactor: convert string formatting to f-strings

.github/workflows/ci.yml, CONTRIBUTING.md, poetry.lock, pyproject.toml
=> ci: add Python 3.10-dev to CI

.github/workflows/ci.yml, poetry.lock, pyproject.toml
=> ci: enable Python 3.10

.readthedocs.yml
=> chore: upgrade docs to Python 3.9

deezer/client.py, deezer/resources.py, tests/test_resources.py
=> feat: deserialize date in `Resource.as_dict()` method

deezer/resources.py, tests/cassettes/TestEpisode.test_as_dict.yaml, tests/cassettes/TestEpisode.test_get_episode.yaml, tests/test_resources.py
=> fix: follow Deezer's format when deserializing datetime

.github/workflows/ci.yml, .github/workflows/semantic-release.yml, deezer/resources.py, tests/cassettes/TestAlbum.test_contributors.yaml, tests/cassettes/TestTrack.test_contributors.yaml, tests/test_resources.py
=> feat: parse album & track contributors

deezer/client.py, deezer/contrib/tornado.py, docs/source/api_reference/toc.rst, docs/source/asynchronous.md, docs/source/index.md, docs/source/installation.md, docs/source/usage.md
=> docs: reword section about authentication

deezer/resources.py, docs/source/api_reference/resources.md, docs/source/api_reference/resources.rst, docs/source/api_reference/resources/album.rst, docs/source/api_reference/resources/artist.rst, docs/source/api_reference/resources/chart.rst, docs/source/api_reference/resources/episode.rst, docs/source/api_reference/resources/genre.rst, docs/source/api_reference/resources/playlist.rst, docs/source/api_reference/resources/podcast.rst, docs/source/api_reference/resources/radio.rst, docs/source/api_reference/resources/track.rst, docs/source/api_reference/resources/user.rst, docs/source/conf.py, docs/source/index.md
=> docs: split documentation for resources into multiple pages

deezer/client.py, deezer/dates.py, deezer/exceptions.py, deezer/pagination.py, deezer/resources.py, oauth.py, tests/test_client.py, tests/test_exceptions.py, tests/test_pagination.py, tests/test_resources.py
=> refactor: refactor type annotations with future style

poetry.lock, pyproject.toml
=> chore: upgrade dependencies

poetry.lock
=> chore: upgrade deps

src/deezer/client.py, src/deezer/resources.py
=> docs: fix a few typos

tox.ini
Committed via https://github.com/asottile/all-repos
=> chore: remove tox file

src/deezer/resources.py, tests/cassettes/TestArtist.test_get_playlists.yaml, tests/cassettes/TestChart.test_get_podcasts.yaml, tests/cassettes/TestGenre.test_get_podcasts.yaml, tests/test_resources.py
Added methods for the following endpoints:
- https://developers.deezer.com/api/artist/playlists (return a list of artist's playlist)
- https://developers.deezer.com/api/genre/podcasts (returns all podcasts for a genre)
- https://developers.deezer.com/api/chart/podcasts (returns the Top podcasts.)
=> feat: get the top podcasts, genre's podcasts and artist's playlists 

src/deezer/__init__.py, tests/test_client.py, tests/test_resources.py
=> fix: add a few classes to top level API

.codespellrc, .pre-commit-config.yaml
=> chore: add more pre-commit hooks

.github/workflows/ci.yml, .github/workflows/semantic-release.yml
Committed via https://github.com/asottile/all-repos
=> fix(deps): revert PSR upgrade

docs/source/api_reference/resources/editorial.rst, docs/source/usage.md
=> docs: fix errors in search usage documentation

docs/source/pagination.md, docs/source/usage.md, src/deezer/client.py, src/deezer/resources/album.py, src/deezer/resources/artist.py, src/deezer/resources/chart.py, src/deezer/resources/editorial.py, src/deezer/resources/genre.py, src/deezer/resources/playlist.py, src/deezer/resources/podcast.py, src/deezer/resources/radio.py, src/deezer/resources/track.py, src/deezer/resources/user.py
=> docs: fix links to resources and pagination classes

.pre-commit-config.yaml, .sourcery.yaml, docs/source/conf.py, pyproject.toml, src/deezer/client.py, src/deezer/pagination.py, src/deezer/resources/resource.py
=> chore: add mypy as pre-commit hook

.codespellrc, src/deezer/client.py, src/deezer/resources/user.py, tests/cassettes/TestClient.test_add_user_following.yaml, tests/cassettes/TestClient.test_get_user_followers[args0].yaml, tests/cassettes/TestClient.test_get_user_followers[args1].yaml, tests/cassettes/TestClient.test_get_user_followings[args0].yaml, tests/cassettes/TestClient.test_get_user_followings[args1].yaml, tests/cassettes/TestClient.test_remove_user_following.yaml, tests/resources/cassettes/TestUser.test_get_followers.yaml, tests/resources/cassettes/TestUser.test_get_followings.yaml, tests/resources/test_user.py, tests/test_client.py
This allows to manage user's friends:
- get the followers 
- get, add or remove a following
Also fix a return type in the doc
=> feat: manage user's friends

.readthedocs.yml
=> chore: simplify readthedocs build

.readthedocs.yml, poetry.lock, pyproject.toml
=> chore: replace docs extra by Poetry group

pyproject.toml
=> fix: add Twitter and Mastodon links to PyPI

README.md, docs/source/index.md
=> docs: improve links between docs and source code

.github/workflows/ci.yml
=> ci: run PSR with noop option on branches

src/deezer/resources/playlist.py, src/deezer/utils.py
=> refactor: extract replicated code into a `get_ids` utility function

src/deezer/client.py, src/deezer/resources/episode.py, tests/resources/cassettes/TestEpisode.test_add_bookmark.yaml, tests/resources/cassettes/TestEpisode.test_remove_bookmark.yaml, tests/resources/test_episode.py
=> feat: add ability to add/remove a bookmark to an episode

src/deezer/client.py, src/deezer/resources/resource.py, src/deezer/resources/user.py, src/deezer/utils.py, tests/resources/cassettes/TestUser.test_add_album_by_id.yaml, tests/resources/cassettes/TestUser.test_add_album_obj.yaml, tests/resources/cassettes/TestUser.test_add_artist_id.yaml, tests/resources/cassettes/TestUser.test_add_artist_obj.yaml, tests/resources/cassettes/TestUser.test_add_playlist_by_id.yaml, tests/resources/cassettes/TestUser.test_add_playlist_failed.yaml, tests/resources/cassettes/TestUser.test_add_playlist_obj.yaml, tests/resources/cassettes/TestUser.test_add_track_id.yaml, tests/resources/cassettes/TestUser.test_add_track_obj.yaml, tests/resources/cassettes/TestUser.test_create_playlist.yaml, tests/resources/cassettes/TestUser.test_follow_by_id_fail.yaml, tests/resources/cassettes/TestUser.test_follow_by_id_ok.yaml, tests/resources/cassettes/TestUser.test_follow_obj.yaml, tests/resources/cassettes/TestUser.test_remove_album_by_id.yaml, tests/resources/cassettes/TestUser.test_remove_album_obj.yaml, tests/resources/cassettes/TestUser.test_remove_artist_id.yaml, tests/resources/cassettes/TestUser.test_remove_artist_obj.yaml, tests/resources/cassettes/TestUser.test_remove_playlist_by_id.yaml, tests/resources/cassettes/TestUser.test_remove_playlist_obj.yaml, tests/resources/cassettes/TestUser.test_remove_track_id.yaml, tests/resources/cassettes/TestUser.test_remove_track_obj.yaml, tests/resources/cassettes/TestUser.test_unfollow_by_id.yaml, tests/resources/cassettes/TestUser.test_unfollow_obj.yaml, tests/resources/test_user.py
Operations:
- Manage Albums in library
- Manage Tracks in library
- Manage Artists in library
- Follow and unfollow other users
- Create a playlist
- Manage playlists in library
=> feat: add methods to `User` resource to create & remove related resources

.github/workflows/ci.yml, pyproject.toml
Committed via https://github.com/asottile/all-repos
=> feat: add official support for Python 3.12

.github/workflows/ci.yml, .github/workflows/codeql.yml, .github/workflows/labels.yml
Committed via https://github.com/asottile/all-repos
=> chore: change checkout action to v4 tag

.readthedocs.yml
=> chore: fix RTD build with Poetry 1.8

README.md, docs/usage.md
=> docs: update language for python REPL blocks

.github/workflows/ci.yml, pyproject.toml
=> ci: ability to release from stable branches

.github/workflows/ci.yml, pyproject.toml
=> ci: ability to release from stable branches [backport]

.pre-commit-config.yaml, README.md, conftest.py, docs/conf.py, src/deezer/auth.py, src/deezer/client.py, src/deezer/resources/playlist.py, src/deezer/resources/resource.py, src/deezer/resources/user.py, tests/resources/test_episode.py, tests/resources/test_radio.py, tests/test_pagination.py
=> chore: switch to Ruff formatter
